# Generated by Django 5.0.6 on 2024-11-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('rut_paciente', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
