# Generated by Django 5.0.6 on 2024-11-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='pacientes_asignados',
            field=models.TextField(blank=True, help_text='Lista de RUTs separados por comas.'),
        ),
    ]
